// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/connesc/cipherio (interfaces: Padding)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPadding is a mock of Padding interface
type MockPadding struct {
	ctrl     *gomock.Controller
	recorder *MockPaddingMockRecorder
}

// MockPaddingMockRecorder is the mock recorder for MockPadding
type MockPaddingMockRecorder struct {
	mock *MockPadding
}

// NewMockPadding creates a new mock instance
func NewMockPadding(ctrl *gomock.Controller) *MockPadding {
	mock := &MockPadding{ctrl: ctrl}
	mock.recorder = &MockPaddingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPadding) EXPECT() *MockPaddingMockRecorder {
	return m.recorder
}

// Fill mocks base method
func (m *MockPadding) Fill(arg0 []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fill", arg0)
}

// Fill indicates an expected call of Fill
func (mr *MockPaddingMockRecorder) Fill(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fill", reflect.TypeOf((*MockPadding)(nil).Fill), arg0)
}
